- name: Delete ec2 instances before removing other AWS resources
  include_role:
    name: "{{ role_item }}"
  vars:
    already_deleted: False
  loop:
    - aws-whoami
    - aws-build-firewall
  loop_control:
    loop_var: role_item

- name: Gather facts about all availabily zones
  amazon.aws.aws_az_info:
    region: "{{ aws_region }}"
  register: reg_aws_az_info

- name: Gather facts about VPC
  amazon.aws.ec2_vpc_net_info:
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ name_prefix }}-vpc"
      "tag:Environment": simple
  register: reg_vpc

- name: Gather facts about all route tables
  community.aws.ec2_vpc_route_table_info:
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ reg_vpc.vpcs[0].id }}"
      "tag:Name": "{{ name_prefix }}-vpc-*"
      "tag:Environment": simple
  register: reg_route_tables
  when: reg_vpc.vpcs is defined and reg_vpc.vpcs | length > 0

- name: Gather facts about all subnets
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ aws_region }}"
    filters:
      availability-zone: "{{ reg_aws_az_info.availability_zones[0].zone_name }}"
      vpc-id: "{{ reg_vpc.vpcs[0].id }}"
      "tag:Name": "{{ name_prefix }}-vpc-*"
      "tag:Environment": simple
  register: reg_subnets
  when: reg_vpc.vpcs is defined and reg_vpc.vpcs | length > 0

- name: Delete igws
  community.aws.ec2_vpc_igw:
    vpc_id: "{{ reg_vpc.vpcs[0].id }}"
    region: "{{ aws_region }}"
    state: absent
  when: reg_vpc.vpcs is defined and reg_vpc.vpcs | length > 0

- name: Delete subnets
  amazon.aws.ec2_vpc_subnet:
    cidr: "{{ item.cidr_block }}"
    vpc_id: "{{ reg_vpc.vpcs[0].id }}"
    region: "{{ aws_region }}"
    state: absent
  loop: "{{ reg_subnets.subnets }}"
  when: reg_vpc.vpcs is defined and reg_vpc.vpcs | length > 0

- name: Delete route tables
  community.aws.ec2_vpc_route_table:
    route_table_id: "{{ item.id }}"
    vpc_id: "{{ reg_vpc.vpcs[0].id }}"
    region: "{{ aws_region }}"
    lookup: id
    state: absent
  loop: "{{ reg_route_tables.route_tables }}"
  when: reg_vpc.vpcs is defined and reg_vpc.vpcs | length > 0

- name: Delete VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ name_prefix }}-vpc"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ aws_region }}"
    state: absent

- name: Delete ec2 key pair
  amazon.aws.ec2_key:
    name: "{{ name_prefix }}-ssh_key"
    region: "{{ aws_region }}"
    state: absent
