mgmt_subnet:
public_subnet:
private_subnet:
ethernet_interfaces:
  - name: ethernet1/1
    dhcp: True
    dhcp_create_default_route: True
    comment: untrust interface
  - name: ethernet1/2
    dhcp: True
    comment: trust interface
virtual_routers:
  - name: vr1
    interfaces:
      - ethernet1/1
      - ethernet1/2
